/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜËÄ 12ÔÂ 27 2018
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void main(void)
 { 
   // Write your code here
   while (1)
      ;
 }